### ISSUE TITLE
multiplication by batchsize

### ISSUE THREAD

**Issue by nsaadati** [gstoica27/ZipIt#20]
Hello, I noticed in the code snippet provided that the results is being multiplied by batch size when calculating the covariance matrix. Could you please explain the rationale behind this multiplication? Additionally, I'm curious why the resulting values are divided by the number of elements. Any insights into these calculations would be greatly appreciated. Thank you.
https://github.com/gstoica27/ZipIt/blob/bcc7c558aadd64964425f4ec1d7efb824a21c2e3/metric_calculators.py#L38

**Comment by nsaadati** [comment]
Is it okay to use the correlation matrix instead of the covariance matrix for the computation?

**Comment by gstoica27** [comment]
Hi, apologies for this very late response! 

For (1) We multiplied by the batch size b/c it may be variable through training. For instance, the last batch may contain fewer elements than the expected batch size.

For (2) It should be, you'll just have to add a line to each matching_function to handle correlation matrices instead of covariance ones. Currently, our covariance matrices are being turned into correlations inside the matching_function code, but if we already have correlation matrices, we do not need to do this.
